baseURL = 'https://alexdwastaken.github.io/Blog/'
languageCode = 'en-us'
title = "Xize's CS184 Blog"
theme = 'FixIt'

[markup]
  _merge = "shallow"
[outputs]
  _merge = "shallow"
[taxonomies]
  _merge = "shallow"